services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER : ${DATABASE_USER}
      POSTGRES_DB : ${DATABASE_NAME}
    volumes:
      - tutorials-go-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  tutorials-go-db:
