// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCredentials = `-- name: GetCredentials :one
SELECT id,password,salt FROM users
WHERE username = $1
`

type GetCredentialsRow struct {
	ID       int32
	Password []byte
	Salt     []byte
}

func (q *Queries) GetCredentials(ctx context.Context, username string) (GetCredentialsRow, error) {
	row := q.db.QueryRow(ctx, getCredentials, username)
	var i GetCredentialsRow
	err := row.Scan(&i.ID, &i.Password, &i.Salt)
	return i, err
}

const getCredentialsById = `-- name: GetCredentialsById :one
SELECT id,password,salt FROM users
WHERE id = $1
`

type GetCredentialsByIdRow struct {
	ID       int32
	Password []byte
	Salt     []byte
}

func (q *Queries) GetCredentialsById(ctx context.Context, id int32) (GetCredentialsByIdRow, error) {
	row := q.db.QueryRow(ctx, getCredentialsById, id)
	var i GetCredentialsByIdRow
	err := row.Scan(&i.ID, &i.Password, &i.Salt)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, password, salt, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Salt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideoUrl = `-- name: GetVideoUrl :one
SELECT url FROM videos
WHERE id = $1 and user_id = $2
`

type GetVideoUrlParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) GetVideoUrl(ctx context.Context, arg GetVideoUrlParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getVideoUrl, arg.ID, arg.UserID)
	var url pgtype.UUID
	err := row.Scan(&url)
	return url, err
}

const insertUsers = `-- name: InsertUsers :one
INSERT INTO users (username,email,password,salt)
VALUES ($1,$2,$3,$4)
RETURNING id
`

type InsertUsersParams struct {
	Username string
	Email    string
	Password []byte
	Salt     []byte
}

func (q *Queries) InsertUsers(ctx context.Context, arg InsertUsersParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertUsers,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Salt,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const insertVideo = `-- name: InsertVideo :exec
INSERT INTO videos (user_id,title,nonce) values ($1, $2, $3)
`

type InsertVideoParams struct {
	UserID int32
	Title  []byte
	Nonce  []byte
}

func (q *Queries) InsertVideo(ctx context.Context, arg InsertVideoParams) error {
	_, err := q.db.Exec(ctx, insertVideo, arg.UserID, arg.Title, arg.Nonce)
	return err
}

const listVideos = `-- name: ListVideos :many
SELECT id, title, nonce FROM videos
WHERE user_id = $1
`

type ListVideosRow struct {
	ID    int32
	Title []byte
	Nonce []byte
}

func (q *Queries) ListVideos(ctx context.Context, userID int32) ([]ListVideosRow, error) {
	rows, err := q.db.Query(ctx, listVideos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVideosRow
	for rows.Next() {
		var i ListVideosRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Nonce); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
